title: Chafik Ferhat
theme: jekyll-theme-academicpages #exemple de thème
show_downloads: true
description:
email: chafik.ferhat@proton.me
github_username: ChafikFe
linkedin: chafik-ferhat  # ton username LinkedIn (sans le /in/)
