title: Chafik Ferhat
theme: jekyll-theme-minimal #exemple de thème
show_downloads: true
description: Data Science Portfolio
email: chafik.ferhat@proton.me
github_username: ChafikFe
linkedin: chafik-ferhat  # ton username LinkedIn (sans le /in/)
